THEORIES:-

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?






THE PURPOSE AND ADVANTAGES OF NUMPY ARE:-

1.numpy is a numerical python (2005 by Travis Oliphant)
2.to manupulating and to store only homogenous data,numpy array is faster.
3.the mathematical computation is fast.
4.we have multiple approaches to generate any array.
5.broadcasting,high speed and performance.

Enhancement of Python's Capabilities:

NumPy enhances Python's capabilities for numerical operations by:

Providing a more efficient and convenient array data structure compared to native Python lists.
Enabling high-performance computing through optimized algorithms and data structures.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

np.mean():- calculates the arithmetic mean of the array elements along a specified axis.

Use np.mean():

When you need a simple arithmetic mean.
When all elements contribute equally to the average.

np.average():- Computes the weighted average of array elements. If no weights are provided, it behaves like np.mean().


Use np.average():

When you need to compute a weighted average.
When different elements of the array should have different levels of importance in the average calculation.

Use np.average():

When you need to compute a weighted average.
When different elements of the array should have different levels of importance in the average calculation.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Reversing a NumPy array can be done easily using slicing:


for 1D array:

In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
reverse_1d = array[::-1]

print("Original 1D array:",array)
print("Reversed 1D array:", reverse_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


For 2d array:

In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
reversed_arr_2d_rows = arr_2d[::-1, :]

print("Original 2D array", arr_2d)
print("Reversed 2D array ", reversed_arr_2d_rows)

Original 2D array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D array  [[7 8 9]
 [4 5 6]
 [1 2 3]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

To check the data type of a NumPy array, you can simply access the .dtype attribute:

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1 = np.array([1.0, 2.0, 3.0])
arr1.dtype

dtype('float64')

In [ ]:
arr1 = np.array(["a","b","c"])
arr1.dtype

dtype('<U1')

THE IMPORTANCE OF MEMORY MANAGEMENT AND PERFORMANCE:

This is important in applications like data analysis, image processing, and machine learning, where efficiency can significantly impact performance.

Operations on arrays with smaller, more specific data types can be faster.

Different libraries may expect inputs in specific data types.



5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

 Ndarrays (n-dimensional arrays) are the core data structure used for representing and manipulating multi-dimensional data.

 The key features are-

 it stores homogenous data

 it has higher efficiency

 it is multidimensional

 it has slicing and indexing


In [13]:
import numpy as np

arr_np = np.array([1, 2, 3, 4, 5])
print("NumPy array:", arr_np)
print("Data type:", arr_np.dtype)

NumPy array: [1 2 3 4 5]
Data type: int64


it is different from lists.

In [14]:
arr_list = [1, 2, 3, 4, 5]
print("Python list:", arr_list)

Python list: [1, 2, 3, 4, 5]


In [16]:
arr = arr_np + 5
print("NumPy array after addition:", arr)

NumPy array after addition: [ 6  7  8  9 10]


In [17]:
arr_add = [x + 5 for x in arr_list]
print("Python list after addition:", arr_add)

Python list after addition: [6, 7, 8, 9, 10]


loop is needed for list,while numpy its not.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operation?

1.ndarrays are stored in contiguous blocks of memory while python list are non-contigous.

2. All elements in a NumPy array are of the same type homogenous,while list are heterogenous.

3.NumPy Offers broadcasting,while python list lacks of build broadcasting.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally.

In [19]:
import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

result_vstack = np.vstack((array1, array2))
result_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:

result_hstack = np.hstack((array1, array2))
result_hstack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

fliplr():-
 Flips an array left to right (horizontally).
 It reverses the order of columns in a 2D array.

 flipud()
 Flips an array up to down (vertically).
 It reverses the order of rows in a 2D array.

In [21]:
import numpy as np
array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
hflip = np.fliplr(array)
hflip

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [22]:
vflip = np.flipud(array)
vflip

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() function in NumPy is used to split an array into multiple sub-arrays.

It Handles Uneven Splits
When splitting an array into a specified number of sections, array_split() handles the case where the number of elements does not evenly divide by the number of sections.

In [24]:
import numpy as np
array = np.arange(10)


split_array = np.array_split(array, 3)
split_array

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

unsplit array

In [25]:
array2 = np.arange(7)
split_array2 = np.array_split(array2, 3)
split_array2

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Vectorization refers to the process of applying operations to entire arrays (or large chunks of data) at once, rather than using explicit loops.

In [26]:
import numpy as np
a = np.random.rand(1000000)
b = np.random.rand(1000000)


result = a + b
result

array([1.80063601, 1.65165872, 0.36158608, ..., 0.39916694, 1.02094554,
       0.99027149])

Broadcasting is a feature that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes without requiring explicit replication of data.

In [27]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
array_1d = np.array([10, 20, 30])


result_broadcast = array_2d + array_1d
result_broadcast


array([[11, 22, 33],
       [14, 25, 36]])

Practical Questions:


1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [28]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
array



array([[98, 83, 68],
       [50, 14, 56],
       [75, 27, 93]])

In [29]:
array.T

array([[98, 50, 75],
       [83, 14, 27],
       [68, 56, 93]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [31]:
import numpy as np

array_1d = np.arange(10)
array_1d



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:

array_2x5 = array_1d.reshape(2, 5)
array_2x5



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
array_5x2 = array_1d.reshape(5, 2)
array_5x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [35]:
import numpy as np
array= np.random.rand(4, 4)
array

array([[0.69278314, 0.37439535, 0.7196724 , 0.95168775],
       [0.57655121, 0.46001848, 0.84555876, 0.44370517],
       [0.51088015, 0.10149857, 0.7091176 , 0.74591736],
       [0.35624873, 0.34737694, 0.79648062, 0.69286045]])

In [37]:
array_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
array_border

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.69278314, 0.37439535, 0.7196724 , 0.95168775,
        0.        ],
       [0.        , 0.57655121, 0.46001848, 0.84555876, 0.44370517,
        0.        ],
       [0.        , 0.51088015, 0.10149857, 0.7091176 , 0.74591736,
        0.        ],
       [0.        , 0.35624873, 0.34737694, 0.79648062, 0.69286045,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [38]:
import numpy as np
array = np.arange(10, 61, 5)
array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

5. Create a NumPy array of strings ['python', 'numpy', 'pandaas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [39]:
import numpy as np
string_array = np.array(['python', 'numpy', 'pandas'])

uppercase = np.char.upper(string_array)
uppercase

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [40]:
lowercase_array = np.char.lower(string_array)
lowercase_array

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [41]:
titlecase_array = np.char.title(string_array)
titlecase_array

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [42]:
import numpy as np
words_array = np.array(['hello', 'world', 'numpy', 'pandas'])
words_array

array(['hello', 'world', 'numpy', 'pandas'], dtype='<U6')

In [43]:
spaced_array = np.char.join(' ', words_array)
spaced_array

array(['h e l l o', 'w o r l d', 'n u m p y', 'p a n d a s'], dtype='<U11')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [44]:
import numpy as np
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])


In [45]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
array2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [47]:
array1+array2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [48]:
array1 - array2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [49]:
array1 * array2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [50]:
array1 / array2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [51]:
import numpy as np

identity= np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
diagonal_elements = np.diagonal(identity)
diagonal_elements


array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [53]:
import numpy as np
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

In [54]:
random_array = np.random.randint(0, 1001, size=100)
random_array

array([293, 390, 814, 508, 930, 848, 837, 903, 725, 974, 195, 666, 594,
       903, 245, 174, 226, 136, 348, 176, 609, 468, 448, 814, 558, 644,
       578, 679, 309, 205, 457, 615,  66,  86, 100, 614, 404, 602, 298,
       933, 382, 119, 492, 316, 561, 618,  62, 782,  54, 205, 431, 788,
       220, 869, 778, 936, 456,  23, 396, 323, 913, 488, 137, 312, 278,
       761, 612,  44, 483, 911, 493, 884, 160, 898, 770, 142,  42, 344,
       996, 477, 745, 666, 724, 997, 954, 423, 326, 788, 588, 520, 250,
       794, 498, 583, 745, 455, 316, 396, 586, 911])

In [55]:
prime_numbers = [num for num in random_array if is_prime(num)]
prime_numbers

[293, 457, 431, 23, 137, 761, 911, 997, 911]

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [63]:
import numpy as np
daily_temperatures = np.random.uniform(15, 35, size=60)
daily_temperatures


array([15.5618072 , 23.24088999, 17.94953088, 20.1708938 , 28.43932545,
       25.92705989, 17.39848674, 20.61655809, 15.29098034, 24.2408924 ,
       22.06214061, 18.86504289, 32.65147435, 24.61663661, 33.32024198,
       24.08535691, 34.11194419, 28.36750277, 24.03601668, 33.25833179,
       33.06030185, 24.08955253, 19.47023949, 20.2307827 , 21.94552314,
       27.28103867, 18.68884499, 18.56855237, 27.68763284, 30.3514099 ,
       34.54876085, 17.26367043, 32.02417086, 21.92392208, 20.90952371,
       23.62639754, 23.65272514, 21.556995  , 24.32442335, 33.75356769,
       28.38341712, 20.29935952, 22.02913192, 31.14896986, 23.08152877,
       32.22045972, 15.0222996 , 21.73019776, 28.53151066, 18.63523705,
       27.13418644, 18.1742981 , 20.7647273 , 33.40191482, 26.44129296,
       30.0909741 , 27.29461741, 24.55770363, 16.81494359, 16.17294832])

In [60]:
num_weeks = len(daily_temperatures) // 7
num_weeks

4

In [64]:
weeks = daily_temperatures.reshape(num_weeks, -1)
weeks

array([[15.5618072 , 23.24088999, 17.94953088, 20.1708938 , 28.43932545,
        25.92705989, 17.39848674, 20.61655809, 15.29098034, 24.2408924 ,
        22.06214061, 18.86504289, 32.65147435, 24.61663661, 33.32024198],
       [24.08535691, 34.11194419, 28.36750277, 24.03601668, 33.25833179,
        33.06030185, 24.08955253, 19.47023949, 20.2307827 , 21.94552314,
        27.28103867, 18.68884499, 18.56855237, 27.68763284, 30.3514099 ],
       [34.54876085, 17.26367043, 32.02417086, 21.92392208, 20.90952371,
        23.62639754, 23.65272514, 21.556995  , 24.32442335, 33.75356769,
        28.38341712, 20.29935952, 22.02913192, 31.14896986, 23.08152877],
       [32.22045972, 15.0222996 , 21.73019776, 28.53151066, 18.63523705,
        27.13418644, 18.1742981 , 20.7647273 , 33.40191482, 26.44129296,
        30.0909741 , 27.29461741, 24.55770363, 16.81494359, 16.17294832]])

In [66]:

weekly_averages = np.mean(weeks, axis=1)
weekly_averages


array([22.69013075, 25.68220205, 25.23510426, 23.7991541 ])